# +title: npm-run.el
#+author: juboba
#+description: Run npm scripts from any package.json in your project
#+keywords: emacs, npm, scripts, monorepo

* Installation

Manually add to your Emacs config:

#+begin_src elisp
(add-to-list 'load-path "/path/to/npm-run")
(require 'npm-run)
#+end_src

Or with [[https://github.com/radian-software/straight.el][straight.el]]:

#+begin_src elisp
(use-package npm-run
  :straight (npm-run :type git :host github :repo "juboba/npm-run"))
#+end_src


* Usage

=M-x npm-run= - Run an npm script from any package.json in your project.

The command will:
1. Find all package.json files in your project
2. If there's more than one, prompt you to select which package (useful for monorepos)
3. Prompt you to select which script to run
4. Execute the script in a compilation buffer

* Configuration

** =npm-run-find-command=
Command to find package.json files (default: =fd=). Uses =find= if =fd= is not available.

#+begin_src elisp
(setq npm-run-find-command "find")
#+end_src

** =npm-run-run-command=
Command to run npm scripts. Can be =npm run=, =yarn=, =pnpm run=, etc.

#+begin_src elisp
(setq npm-run-run-command "yarn")  ; Use yarn instead of npm
#+end_src

** =npm-run-show-ansi-colors=
Whether to show ANSI colors in the output buffer (default: =t=).

#+begin_src elisp
(setq npm-run-show-ansi-colors nil)  ; Disable ANSI colors
#+end_src

* Requirements

- Emacs 28.1+
- =fd= or =find= command-line tool for finding package.json files

* Keybindings

You can bind =npm-run= to a key for quick access:

#+begin_src elisp
(define-key global-map (kbd "C-c n") 'npm-run)
#+end_src

* License

GPL-3.0
